G=../..

CC=g++

#ADDONSOBJS=$(patsubst %.cpp,%.o,$(wildcard $G/CommBase/*.cpp))	\
#			$(patsubst %.cpp,%.o,$(wildcard $G/ServBase/*.cpp))	\
#			$G/SendConfig/SendConfig.o

ADDONSOBJS=$G/llib/libCommBase.a	\
			$G/llib/libtinyxml.a	\
			$G/llib/libjrtp.a	\
			$G/llib/libsocks5.a	

ifdef WEBCON_HAS_FILELOG
	ADDONSFLAGS+=-DWEBCON_HAS_FILELOG
else
ifdef WEBCON_HAS_SYSLOG
	ADDONSFLAGS+=-DWEBCON_HAS_SYSLOG
else
ifdef WEBCON_HAS_STDLOG
	ADDONSFLAGS+=-DWEBCON_HAS_STDLOG
endif
endif
endif

ifdef WEBCON_HAS_PRINT_DEBUG
	ADDONSFLAGS+=-DWEBCON_HAS_PRINT_DEBUG
endif

ifdef WEBCON_HAS_SAFEDOG
	ADDONSFLAGS+=-DWEBCON_HAS_SAFEDOG 
endif

ifdef WEBCON_HAS_DEMODOG
	ADDONSFLAGS+=-DWEBCON_HAS_DEMODOG
endif

ifdef OUR_DEMO_VER
	ADDONSFLAGS+=-DOUR_DEMO_VER
endif

ADDONSFLAGS+=-D__LINUX__
#ADDONSFLAGS+=-D__TXT_MODE__
ADDONSFLAGS+=-DVER_FOR_ANDROID_

FLAGS=-W -g	\
	-I./include	\
	-I$G/CommBase/jni/include \
	-I$G/socks5/jni/include/	\
	-I$G/NetCtrlDll/jni/include	\
	-I$G/FCNetACLib/jni/include	\
	-I$G/jrtplib-2.7/jni/	\
	-I$G/tinyxmllib/jni/include	\
	-L$G/jrtplib-2.7	\
	$(ADDONSFLAGS)		\
	-L../../llib

CCFLAGS=$(FLAGS) -c
#CFLAGS=$(FLAGS) -lACE -lcrypt
CFLAGS=$(FLAGS) -lpthread -ldl
RM=rm -f core.* *.log

BASESERVOBJS=$(ADDONSOBJS)
