G=..

CC=g++

ADDONSOBJS=$(patsubst %.cpp,%.o,$(wildcard $G/CommBase/*.cpp))	\
			$(patsubst %.cpp,%.o,$(wildcard $G/ServBase/*.cpp))	\
			$G/SendConfig/SendConfig.o	\
			$G/tinyxmllib/libtinyxml.a	\
			$G/jrtplib-2.7/libjrtp.a	\
			$G/socks5/libsocks5.a

#$G/CreateKey/libKey.a	

#$G/AlarmAlgorithmLib/libalarm.a

ifdef WEBCON_HAS_FILELOG
	ADDONSFLAGS+=-DWEBCON_HAS_FILELOG
else
ifdef WEBCON_HAS_SYSLOG
	ADDONSFLAGS+=-DWEBCON_HAS_SYSLOG
else
ifdef WEBCON_HAS_STDLOG
	ADDONSFLAGS+=-DWEBCON_HAS_STDLOG
endif
endif
endif

ifdef WEBCON_HAS_PRINT_DEBUG
	ADDONSFLAGS+=-DWEBCON_HAS_PRINT_DEBUG
endif

ifdef WEBCON_HAS_SAFEDOG
	ADDONSFLAGS+=-DWEBCON_HAS_SAFEDOG 
endif

ifdef WEBCON_HAS_DEMODOG
	ADDONSFLAGS+=-DWEBCON_HAS_DEMODOG
endif

ifdef OUR_DEMO_VER
	ADDONSFLAGS+=-DOUR_DEMO_VER
endif



ADDONSFLAGS+=-D__LINUX__
ADDONSFLAGS+=-D__TXT_MODE__
ADDONSFLAGS+=-DUSE_ACE_VER
ADDONSFLAGS+=-DACE_HAS_EVENT_POLL

ADDONSFLAGS+=-D__ShuangXian__

FLAGS=-W -g	\
	-I./include	\
	-I$G/CommBase/include	\
	-I$G/ServBase/include	\
	-I$G/NetCtrlDll/include	\
	-I$G/FCNetACLib/include	\
	-I$G/SendConfig/include	\
	-I$G/jrtplib-2.7	\
	-I$G/tinyxmllib/include	\
	-I$G/CreateKey	\
	-I$(ACE_ROOT)	\
	-I$G/AlarmAlgorithmLib/include	\
	\
	-L$G/jrtplib-2.7	\
	-L$(ACE_ROOT)/ace	\
	$(ADDONSFLAGS)		\
	-L../../lib

CCFLAGS=$(FLAGS) -c
CFLAGS=$(FLAGS) -lACE -lcrypt
RM=rm -f core.* *.log

BASESERVOBJS=$(ADDONSOBJS)
